name: mot
description: A sober and efficient alternative to state management in Dart and Flutter. Subscribe and forget.
version: 0.0.1
homepage: https://github.com/frr149/mot
repository: https://github.com/frr149/mot
issue_tracker: https://github.com/frr149/mot/issues

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.25.0
  glados: ^0.6.0
  mocktail: ^1.0.0
